name: 'acore-linux-build-action'
description: 'GitHub Action for AzerothCore linux build'
author: 'locus313'

runs:
  using: composite
  steps:
    - name: Configure OS
        run: source ./acore.sh install-deps
        env:
          CONTINUOUS_INTEGRATION: true
    - name: Create conf/config.sh
        run: source ./apps/ci/ci-conf.sh
    - name: Import db
        run: source ./apps/ci/ci-import-db.sh
    - name: Build
        run: source ./apps/ci/ci-compile.sh
    - name: Dry run
        run: source ./apps/ci/ci-worldserver-dry-run.sh
    - name: Check startup errors
        run: source ./apps/ci/ci-error-check.sh
    - name: Run unit tests
        run: source ./apps/ci/ci-run-unit-tests.sh
